### ISSUE TITLE
lib/netstandard2.1 contains  netstandard2.0 version => Lost support for valueTask

### ISSUE THREAD

**Issue by thinkbeforecoding** [TheAngryByrd/IcedTasks#20]
**Describe the bug**
The 0.5.2 version of IcedTasks has lost support for valueTask in netstandard2.1

**To Reproduce**
1. Update IcedTasks in a net6.0+ or netstandard2.1 project using valueTask
2. Build
3. See error: valueTask is not defined

The lib/netstandard2.1 directory of the nuget contains the netstandard2.0 build of the dll.

**Expected behavior**
netstandard2.1 lib should be packaged, valueTask should be available.

**Desktop (please complete the following information):**
 - OS: all
 - Version 0.5.2

**Comment by thinkbeforecoding** [comment]
The current 0.5.2 should probably be unlisted from nuget.org

#21 is fixing this.

**Comment by TheAngryByrd** [comment]
I went an unlisted the package. Thanks again!
