### ISSUE TITLE
Implement taskSeq

### ISSUE THREAD

**Issue by TheAngryByrd** [TheAngryByrd/IcedTasks#5]
**Is your feature request related to a problem? Please describe.**

Move the [taskSeq](https://github.com/dotnet/fsharp/blob/b9942004e8ba19bf73862b69b2d71151a98975ba/tests/benchmarks/CompiledCodeBenchmarks/TaskPerf/TaskPerf/taskSeq.fs) implementation to here

**Describe the solution you'd like**

Move the Fsharp.Core implementation here and finish it.

**Describe alternatives you've considered**

I'm still thinking this should be part of `FSharp.Control.AsyncSeq` as they're more closely related.

**Additional context**

 https://github.com/fsprojects/FSharp.Control.AsyncSeq/pull/151

**Comment by abelbraaksma** [comment]
That page gives me a 404, I think you meant this? https://github.com/dotnet/fsharp/blob/d5312aae8aad650f0043f055bb14c3aa8117e12e/tests/benchmarks/CompiledCodeBenchmarks/TaskPerf/TaskPerf/taskSeq.fs

**Comment by TheAngryByrd** [comment]
Thats what I get for not using a permalink. Thanks!

**Comment by dsyme** [comment]
Just to link to https://github.com/abelbraaksma/TaskSeq/ where we're doing TaskSeq

**Comment by abelbraaksma** [comment]
Which will now redirect to its new home: https://github.com/fsprojects/FSharp.Control.TaskSeq.
